
services:
  ui:
    build: .
    expose:
      - 3000
    env_file:
      - .env.local
    volumes:
      - static:/app/static/
      - pages:/app/.next/server/app/

  nginx:
    build: ./nginx
    ports:
    # if i map 80:80 then i will be able to access my next app at http://localhost instead of http://localhost:1336
      - 1336:80
    volumes:
      - static:/app/static/
      - pages:/app/pages/
    depends_on:
      - ui


# here creating a docker volume
volumes:
  static:
  pages: